services:
  universal_hair_dv_db:
    container_name: universal_hair_dv_db
    image: postgres
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - universal_hair_dv
    restart: unless-stopped

networks:
  universal_hair_dv:
    driver: bridge

volumes:
    db:

