server:
  port: 8080
  error:
    include-message: always
  servlet:
    multipart:
    max-file-size: 10MB
    max-request-size: 10MB

  project:
    image: images/
  main:
    web-application-type: servlet

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/universal_hair
    username: sidof
    password: sidof1/@
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

application:
  title: UNIVERSAL HAIR
  version: v1